### ISSUE TITLE
Vanilla 2.1

### ISSUE THREAD

**Issue by exetico** [daigo75/vanilla-badges#1]
Hello, 

Please don't see this as a issue. I only want to hear about you have spending time with this plugin with Vanilla 2.1.

I can see that Vanilla Logger and AeliaFoundationClasses should work, but i can't enable this plugin :-) 

Thanks for your time.

**Comment by daigo75** [comment]
Hi Tobias,
I'm not sure I understood your message. I haven't modified the Awards plugin in almost two years now. Last time I tried it on Vanilla 2.1 I used 2.1b2 (a Beta version), therefore it might not work properly on the official release.

Since I shifted my focus on a different platform, I don't follow Vanilla Forums very frequently, and there are no current plans to review the Awards plugin for Vanilla 2.1 or 2.2. Furthermore, the YAGA application is now more powerful than the Awards plugin, and it might be a better choice.
